language: python
dist: xenial
python:
- 3.7
- 3.6
- 3.5
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    python: 3.6
    repo: molssi-seamm/lammps_step
    tags: true
  user: seamm
  password:
    secure: CgJ8o+1wXr9mkcOYxWa00SzKyN3MmpM5YK83ne2MBj7fGk03T+3jqWT1a31TcCrls/eSqISbWuZZxdd04C7XNtlS5QBgtIpi5uXcNntfND6jvAZzO40AXXWlagEF/Ch915PyJWeoLajTBE+BMQSxGd9hC3g1YnL12wCmWJ1cY8VSLTfmED2mEydn731hJFTDUJlgkHXE9eoYLZ2txPB90sc3NxPTdVHWhib2495OCwshPdeMqzcnfTrSQHDBwT3gNqCEhrDfrz6pVN69GizhwbW0zvydf+VsyTWIsgUg06TB8W3pio5gMHQgbvXz9TieSAZynyVcO6e4j0bwRUOMUYEThroUgoFLFOoW3V2D+HBisGqpkTcrQ/Ne9Gq8tX4k1IyxmeMzyJPqErO41KbXDms9YSSylIL+M1wRWTcYodp3YIxsDKtekdtWn4goaZWxpmYYldrw5jhRS4Cu7rqZXZKB25KV0CMBc4tTUQJygIFBiQNnULiLbjEKABV/OUrp50jl8yDZNTsrhLyJhUf1WXYIGTXZ1Org7+pYtd7GLhlPMQxEkIMrQ5pxUdrkmSEjMC5eqAkSvZu7GXPfb6iXnVp8WykExjKVNbpXedMyxfRRbA8k0aaJjgsNhYfPYaBG1jWDjMcO6cvUv1GhXwxhvcsB8SJ2s3AkQbM3UxtvJGc=
matrix:
  fast_finish: true
stages:
- lint
- check
- test
install:
- pip install -U tox-travis
- pip install -U codecov
jobs:
  include:
  - stage: lint
    script: tox -e lint
    python: '3.6'
script: tox -e coverage
after_success:
- codecov -e TOX_ENV
