name: BranchCI

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  build-ubuntu:
    name: Light CI for branch
    uses: molssi-seamm/devops/.github/workflows/BranchCI.yaml@main
    with:
      src : lammps_step
